-- Restart-Resilient Autonomy Phase — Phase 2 (Durable trade lifecycle persistence)
--
-- Replaces the production runtime's in-memory-only TradeLifecycleStore (InMemoryTradeLifecycleStore
-- — see src/lib/hermes-execution/trade-lifecycle/trade-lifecycle-store.ts's own top-of-file comment,
-- "deliberately no such implementation exists yet") with a durable, per-user table. Written
-- exclusively by the standalone Hermes trading-runtime process (service-role client +
-- HERMES_SUPABASE_USER_ID — the same pattern trade_candidates/trade_performance already establish).
--
-- Additive only: no existing table, column, or policy is altered or dropped. `id` is a plain
-- app-generated string (a real UUID value, generated by TradeLifecycleService's own idGenerator —
-- see that file's own doc comment on why the pre-existing sequential "trade-lifecycle-N" counter was
-- replaced), matching trade_performance.trade_id's own established "app-generated string, not a
-- database-generated uuid" convention — this table's own `id` column is `text`, not `uuid`, for the
-- same reason: the application, not Postgres, is the authority on this identifier.
--
-- Column selection: the fields the mission explicitly requires "at least" are first-class, queryable
-- columns; everything else TradeLifecycleRecord also carries (decision reasoning, market data
-- snapshot, intelligence summary, portfolio risk decision, MFE/MAE, error details) is folded into
-- one JSONB `detail` column — the exact same "schemaless blob alongside first-class columns"
-- convention trade_candidates.execution_snapshot already established, chosen for the same reason:
-- some of those fields (marketDataSnapshot/intelligenceSummary) are optional and only ever a
-- best-effort audit trail, never queried on their own.
--
-- Pre-deployment hardening pass (this migration has never been applied anywhere — safe to edit in
-- place rather than bolt a follow-up migration on top): adds the constraints a safety review of the
-- restart-resilient-autonomy implementation found missing before this table could be trusted to
-- enforce, not merely record, "one active position per broker slot" / "one active position per
-- strategy+instrument" / status-consistent rows. See each constraint's own comment for the specific
-- defect it closes.

-- Supporting constraint on trade_candidates (0024) so trade_lifecycle_records.candidate_id can be
-- verified — at the database level — to reference a candidate belonging to the SAME user, not just
-- any existing candidate row. Purely additive and non-restrictive in practice: trade_candidates.id
-- is already a primary key (globally unique on its own), so (id, user_id) is trivially satisfiable
-- for every existing and future row — this adds no new uniqueness requirement, it only exposes the
-- existing guarantee in the shape a composite foreign key needs to reference. Guarded with an
-- existence check so this migration stays safely re-runnable, matching this schema's own
-- "if not exists" / "drop policy if exists" idempotency convention (plain `add constraint` has no
-- `if not exists` form in Postgres).
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'trade_candidates_id_user_id_key'
  ) then
    alter table trade_candidates
      add constraint trade_candidates_id_user_id_key unique (id, user_id);
  end if;
end $$;

create table if not exists trade_lifecycle_records (
  id text primary key,
  user_id uuid not null references auth.users (id) on delete cascade,

  -- Nullable: a record adopted from an orphaned broker position (position-reconciliation.ts) has no
  -- originating TradeCandidate to reference — genuinely unknown, never a guessed row id. Ownership
  -- (when a candidate_id IS present) is enforced by the composite foreign key below, not by this
  -- column definition alone.
  candidate_id uuid,

  strategy_id text not null,
  strategy_version integer not null check (strategy_version > 0),
  instrument text not null,

  broker_provider text not null,
  -- Nullable until the position is actually OPEN (a record starts at DECISION_CREATED, before any
  -- broker call has happened at all) — see status consistency check constraint below.
  broker_position_id text,
  broker_order_id text,

  side text not null check (side in ('BUY', 'SELL')),
  sizing_mode text not null check (sizing_mode in ('UNITS', 'NOTIONAL')),
  quantity numeric not null check (quantity > 0),

  -- CLOSED_UNRECONCILED added by the runtime state-machine hardening pass (see
  -- trade-lifecycle/types.ts's own VALID_TRANSITIONS doc comment): a terminal outcome distinct from
  -- CLOSED, reached when reconciliation confirms the broker no longer holds a position this runtime
  -- once tracked as OPEN/CLOSE_REQUESTED/CLOSE_FAILED, but this runtime never obtained a confirmed
  -- exit price/P&L for it. exit_price/realised_pnl stay null forever on such a row — never
  -- fabricated — while closed_at/exit_reason are still recorded so the row is genuinely terminal.
  --
  -- EXECUTION_ABANDONED and EXECUTION_RECONCILIATION_REQUIRED added by the crash-window-recovery
  -- pass (see runtime/lifecycle-recovery.ts): EXECUTION_ABANDONED is terminal — a stale
  -- DECISION_CREATED/APPROVED/EXECUTION_SUBMITTED record proven, against the broker's own state, to
  -- never have (or no longer have) a real order/position. EXECUTION_RECONCILIATION_REQUIRED is NOT
  -- terminal — an EXECUTION_SUBMITTED record whose fate could not be determined (broker read
  -- failure, or ambiguous multiple matches); it stays inside active uniqueness, blocking a fresh
  -- entry, until a later sweep resolves it to OPEN or EXECUTION_ABANDONED.
  status text not null check (status in (
    'DECISION_CREATED', 'RISK_REJECTED', 'APPROVED', 'EXECUTION_SUBMITTED',
    'OPEN', 'CLOSE_REQUESTED', 'CLOSED', 'EXECUTION_FAILED', 'CLOSE_FAILED', 'CLOSED_UNRECONCILED',
    'EXECUTION_ABANDONED', 'EXECUTION_RECONCILIATION_REQUIRED'
  )),

  entry_price numeric check (entry_price is null or entry_price > 0),
  -- Frozen from the originating TradeCandidate when one exists; null for an adopted orphaned
  -- position (genuinely unknown — never reinterpreted as 0 or any other guessed value).
  stop_loss numeric check (stop_loss is null or stop_loss > 0),
  take_profit numeric check (take_profit is null or take_profit > 0),

  opened_at timestamptz,
  closed_at timestamptz,
  exit_price numeric check (exit_price is null or exit_price > 0),
  exit_reason text,
  realised_pnl numeric,

  -- Everything else TradeLifecycleRecord carries — see this migration's own top-of-file comment.
  detail jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- candidate_id must never refer to another user's trade candidate. When candidate_id is null
  -- (orphan adoption) Postgres does not enforce a multicolumn foreign key at all, so this imposes no
  -- constraint on that path — it only fires when a candidate_id is actually present.
  --
  -- Deliberately NOT "on delete set null" (which the pre-hardening single-column version used):
  -- user_id is NOT NULL on this table, and a composite FK's ON DELETE SET NULL nulls every column in
  -- the FK together, which would violate that not-null constraint the instant a referenced candidate
  -- row was deleted. trade_candidates rows are never deleted individually anywhere in this codebase
  -- today (the repository exposes no delete method; the only removal path is cascading from an
  -- auth.users deletion, which independently cascades THIS table's own user_id FK at the same
  -- moment) — so the default NO ACTION is never actually exercised by current application behaviour,
  -- and is strictly safer than silently orphaning a still-referenced candidate_id if that changes.
  constraint trade_lifecycle_records_candidate_user_fk
    foreign key (candidate_id, user_id) references trade_candidates (id, user_id),

  -- detail must be a JSON object (never an array, scalar, or null).
  constraint trade_lifecycle_records_detail_is_object
    check (jsonb_typeof(detail) = 'object'),

  -- closed_at cannot precede opened_at.
  constraint trade_lifecycle_records_closed_not_before_opened
    check (closed_at is null or opened_at is null or closed_at >= opened_at),

  -- OPEN, CLOSE_REQUESTED, CLOSE_FAILED and CLOSED all require broker_position_id, entry_price and
  -- opened_at. Verified against both record-creation paths: the normal candidate-execution path
  -- always has these by the time it reaches OPEN, and the orphan-adoption path
  -- (position-reconciliation.ts) refuses to adopt a broker position at all when the broker's own
  -- reported amount/openRate is missing — so entry_price/opened_at/broker_position_id are always
  -- genuinely known, never guessed, by the time a row can reach any of these four statuses.
  -- stop_loss/take_profit are deliberately NOT required here: an adopted orphan legitimately has
  -- neither (no originating decision ever set them), and still reaches OPEN.
  constraint trade_lifecycle_records_open_status_requires_broker_fields
    check (
      status not in ('OPEN', 'CLOSE_REQUESTED', 'CLOSE_FAILED', 'CLOSED', 'CLOSED_UNRECONCILED')
      or (broker_position_id is not null and entry_price is not null and opened_at is not null)
    ),

  -- CLOSED requires closed_at, exit_price and exit_reason. realised_pnl is included here too, even
  -- though it was only asked to be assessed for nullability: recordClosed() in
  -- trade-lifecycle-service.ts always computes and sets realised_pnl in the very same transition
  -- that sets closed_at/exit_price/exit_reason — there is no code path that reaches CLOSED without
  -- it — so requiring it costs nothing against current behaviour and closes off a future bug (a
  -- close recorded without a P&L figure) that would otherwise silently corrupt downstream
  -- trade-performance reporting.
  constraint trade_lifecycle_records_closed_requires_exit_fields
    check (
      status <> 'CLOSED'
      or (closed_at is not null and exit_price is not null and exit_reason is not null and realised_pnl is not null)
    ),

  -- CLOSED_UNRECONCILED requires closed_at and exit_reason (this row IS genuinely terminal — see
  -- its own status-comment above) but deliberately does NOT require exit_price/realised_pnl: this
  -- status exists specifically for the case where those figures are genuinely unknown, and
  -- position-reconciliation.ts must never fabricate them. Not made mutually exclusive with a future
  -- human manually annotating a confirmed exit price after the fact — only the null case is
  -- required, not enforced.
  constraint trade_lifecycle_records_closed_unreconciled_requires_fields
    check (
      status <> 'CLOSED_UNRECONCILED'
      or (closed_at is not null and exit_reason is not null)
    ),

  -- EXECUTION_ABANDONED requires closed_at and exit_reason too (crash-window-recovery pass) — same
  -- shape as CLOSED_UNRECONCILED's own constraint, for the same reason: this row is genuinely
  -- terminal (recovery.ts proved no real order/position exists), but deliberately does NOT require
  -- broker_position_id/entry_price/opened_at (unlike CLOSED_UNRECONCILED, a record can reach this
  -- status having never had any of those — e.g. abandoned straight from DECISION_CREATED).
  constraint trade_lifecycle_records_execution_abandoned_requires_fields
    check (
      status <> 'EXECUTION_ABANDONED'
      or (closed_at is not null and exit_reason is not null)
    )
);

-- Every read in SupabaseTradeLifecycleStore (getById/list/listOpen/listClosed/update) filters by
-- user_id, so it is always the leading column here — never a bare single-column index on the other
-- field alone.
create index if not exists trade_lifecycle_records_user_status_idx
  on trade_lifecycle_records (user_id, status);
create index if not exists trade_lifecycle_records_user_strategy_instrument_idx
  on trade_lifecycle_records (user_id, strategy_id, instrument);
create index if not exists trade_lifecycle_records_user_broker_position_idx
  on trade_lifecycle_records (user_id, broker_position_id);
create index if not exists trade_lifecycle_records_user_candidate_idx
  on trade_lifecycle_records (user_id, candidate_id);

-- A partial unique index preventing more than one active lifecycle record for the same user_id,
-- broker_provider and broker_position_id. "Active" = OPEN, CLOSE_REQUESTED, CLOSE_FAILED or
-- EXECUTION_RECONCILIATION_REQUIRED — the statuses that mean "this real broker position is not yet
-- confirmed closed/gone" (EXECUTION_RECONCILIATION_REQUIRED included defensively: it typically has
-- no broker_position_id yet — that's exactly why it's ambiguous — but if one is ever known, it must
-- still count). CLOSE_FAILED is deliberately included: a safety review of position-reconciliation.ts
-- found that listOpen()'s own in-memory OPEN_STATUSES excludes CLOSE_FAILED, which let
-- reconciliation silently adopt a SECOND lifecycle record for a broker position whose close attempt
-- had merely failed. This index turns that silent duplicate-adoption bug into a loud, fail-closed
-- constraint violation. CLOSED/CLOSED_UNRECONCILED/EXECUTION_ABANDONED are excluded on purpose: all
-- three are terminal outcomes, and a genuinely new future position could legitimately reuse the same
-- broker_provider/instrument once a prior one is fully resolved. broker_position_id is null for
-- every status before OPEN, and Postgres never treats NULLs as duplicates in a unique index, so
-- those rows are unaffected regardless of the WHERE clause.
create unique index if not exists trade_lifecycle_records_active_broker_position_uidx
  on trade_lifecycle_records (user_id, broker_provider, broker_position_id)
  where status in ('OPEN', 'CLOSE_REQUESTED', 'CLOSE_FAILED', 'EXECUTION_RECONCILIATION_REQUIRED');

-- A partial unique index preventing duplicate active lifecycle records for the same user_id,
-- strategy_id and instrument, under the current one-position-per-strategy/instrument model. Scoped
-- wider than the index above (DECISION_CREATED, APPROVED and EXECUTION_SUBMITTED are included too,
-- alongside OPEN/CLOSE_REQUESTED/CLOSE_FAILED/EXECUTION_RECONCILIATION_REQUIRED) because the
-- duplicate-entry race this is meant to close can occur before a broker_position_id ever exists —
-- e.g. two concurrent cycles both passing an in-app duplicate check and both submitting an order
-- for the same strategy+instrument. EXECUTION_RECONCILIATION_REQUIRED must remain active: an
-- unresolved crash-window record still blocks a fresh entry until a later recovery sweep resolves
-- it. RISK_REJECTED, CLOSED, EXECUTION_FAILED, CLOSED_UNRECONCILED and EXECUTION_ABANDONED are
-- excluded: all are terminal outcomes that free up the strategy+instrument slot for a genuinely new
-- attempt.
create unique index if not exists trade_lifecycle_records_active_strategy_instrument_uidx
  on trade_lifecycle_records (user_id, strategy_id, instrument)
  where status in (
    'DECISION_CREATED', 'APPROVED', 'EXECUTION_SUBMITTED', 'OPEN', 'CLOSE_REQUESTED', 'CLOSE_FAILED',
    'EXECUTION_RECONCILIATION_REQUIRED'
  );

alter table trade_lifecycle_records enable row level security;

-- Same RLS shape as trade_candidates: the standalone runtime process (service role) does all real
-- reads/writes and bypasses RLS entirely, but real policies are still defined here — never rely on
-- RLS being silently bypassed as the only reason access works (matching trade_candidates/
-- trade_performance's own established discipline).
drop policy if exists "Users can view their own trade lifecycle records" on trade_lifecycle_records;
create policy "Users can view their own trade lifecycle records"
  on trade_lifecycle_records for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own trade lifecycle records" on trade_lifecycle_records;
create policy "Users can insert their own trade lifecycle records"
  on trade_lifecycle_records for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own trade lifecycle records" on trade_lifecycle_records;
create policy "Users can update their own trade lifecycle records"
  on trade_lifecycle_records for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

comment on table trade_lifecycle_records is
  'Restart-Resilient Autonomy Phase. Durable replacement for the production runtime''s in-memory-only TradeLifecycleStore — survives PM2 restarts. One row per open-to-close position lifecycle, including positions adopted from an orphaned broker read (no originating candidate) via position-reconciliation.ts.';
comment on column trade_lifecycle_records.id is
  'App-generated (TradeLifecycleService''s own idGenerator, a real UUID string) — text, not a database-generated uuid, matching trade_performance.trade_id''s own established convention.';
comment on column trade_lifecycle_records.broker_position_id is
  'The broker''s OWN durable position identifier (e.g. eToro''s numeric positionID, stringified) — the field position-reconciliation.ts actually matches a live broker position against, never strategy_id/instrument alone once this is available.';
comment on column trade_lifecycle_records.detail is
  'Everything else TradeLifecycleRecord carries (decisionReasons, confidence, marketDataSnapshot, intelligenceSummary, portfolioRiskDecision, realisedPnlPercent, holdingDurationMs, MFE/MAE, error) — schemaless, matching trade_candidates.execution_snapshot''s own convention.';
comment on constraint trade_lifecycle_records_candidate_user_fk on trade_lifecycle_records is
  'Composite FK (candidate_id, user_id) -> trade_candidates (id, user_id): candidate_id can never reference a candidate owned by a different user. Relies on trade_candidates_id_user_id_key (added by this migration) for the referenced side.';
