import { Badge } from "@/components/ui/Badge";
import { SectionPanel } from "@/components/ui/SectionPanel";
import type { StrategyScore } from "@/lib/types";
import { agreementLevelClasses, recommendationClasses, signalToneClasses } from "@/lib/utils/style";

interface GeneratedByPanelProps {
  score: StrategyScore;
}

// The compact "who voted what, and what did it add up to" summary shown above the
// Recommendation panel — see StrategyBreakdownPanel for the fuller per-strategy detail
// (evidence, contribution) and AgreementPanel for why the agreement level is what it is.
export function GeneratedByPanel({ score }: GeneratedByPanelProps) {
  return (
    <SectionPanel
      title="Generated by"
      description={`${score.results.length} deterministic strategies evaluated for ${score.instrumentSymbol}`}
    >
      <div className="divide-y divide-base-700/60">
        {score.results.map((result) => (
          <div key={result.strategyId} className="flex items-center justify-between gap-4 px-5 py-3">
            <span className="text-sm text-ink-100">{result.strategyName}</span>
            <div className="flex items-center gap-3">
              <Badge className={signalToneClasses(result.signal)}>{result.signal}</Badge>
              <span className="w-12 text-right text-sm text-ink-300">{result.confidence}%</span>
            </div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 gap-4 border-t border-base-700 px-5 py-4 sm:grid-cols-3">
        <div className="flex flex-col gap-1">
          <span className="text-xs text-ink-500">Overall recommendation</span>
          <Badge className={`w-fit ${recommendationClasses(score.overallRecommendation)}`}>
            {score.overallRecommendation}
          </Badge>
        </div>
        <div className="flex flex-col gap-1">
          <span className="text-xs text-ink-500">Confidence</span>
          <span className="text-lg font-semibold text-ink-100">{score.overallConfidence}%</span>
        </div>
        <div className="flex flex-col gap-1">
          <span className="text-xs text-ink-500">Agreement</span>
          <Badge className={`w-fit ${agreementLevelClasses(score.agreement)}`}>{score.agreement}</Badge>
        </div>
      </div>
    </SectionPanel>
  );
}
